### PR TITLE
FIX Identify correct class/method for query trace

### PR DESCRIPTION
**Pull request by GuySartorelli**
## Issue
- https://github.com/lekoala/silverstripe-debugbar/issues/152

### CODE REVIEW

**Review by emteknetnz — CHANGES_REQUESTED** [review]
Code looks fine, looking at this pre-patch things looked very wrong

Just to confirm, are we expecting to have a large increase in the number of database calls being traced?

Before:
image

After:
image

**Comment by GuySartorelli** [comment]
Can't reproduce that - you may have done something different in one of those page loads, maybe?

**Review by emteknetnz — APPROVED** [review]
OK it'll be something wrong with setup at my end

LGTM

**Comment by GuySartorelli** [comment]
This was approved by a core committer, so I'm self-merging.

**Pull request merged**
