### PR TITLE
Switch JS and CSS to SCSS and use Yarn for building

### PR DESCRIPTION
**Pull request by Firesphere**
The SCSS is generated from the existing CSS, added docs around contributing. Added icons while at it to messages.

### CODE REVIEW

**Comment by Firesphere** [comment]
Fixing the awesome package.json!

**Comment by Firesphere** [comment]
Ready for PR. Package.json fixed.

**Comment by Firesphere** [comment]
Note: The SCSS is generated by an automated CSS to SCSS system. I sanity checked it and no changes in the resulting CSS, but the SCSS could probably use some more cleaning

**Comment by robbieaverill** [comment]
Just noting comments from Slack:

* assets/debugbar.css etc is an example of the PHP DebugBar default assets that were copied through and put in a place that's not obvious that they're third party
* we shouldn't modify them
* it'd be nice to move them to assets/vendor/phpdebugbar for example so it's more obvious they shouldn't be touched
* customisations in this file (there are some) should be moved to a new file which can be processed by a SASS compiler
* same goes for any modifications to the default vendor's javascript files - any custom widgets should already be in the `javascript/` folder

**Comment by Firesphere** [comment]
Although I agree with you, I consider any modifications and splitting up beyond the scope of this PR. This is an initial "Let's move it to using Yarn", not an actual proper JS/(S)CSS cleanup. I would like to have that done in a separate PR.

Things to be done after this initial PR:
- Split out the custom JS and the vendor JS
- Make variables out of all the colours etc.
- Switch from directly injected FA icons to using FA itself

**Review by robbieaverill — CHANGES_REQUESTED** [review]
Please hold this PR until we are finished with our improvements. We will aim to separate customisatioms from the underlying package assets to make this easier for you.

**Comment by Firesphere** [comment]
👍

**Comment by robbieaverill** [comment]
Let's revisit this when #65 has been done @Firesphere - perhaps using the SilverStripe webpack module instead as it's now the standard for SS4

**Comment by Firesphere** [comment]
I'll leave that up to you.

**Comment by Firesphere** [comment]
Just to check, you are aware Yarn is just a wrapper _around_ webpack, that makes it simpler to use, right? It literally calls webpack in `package.json` "We should use webpack" is not an argument against Yarn.

**Comment by robbieaverill** [comment]
Yep, I was referring to using laravel mix. The compilation binary doesn't really matter, although yarn is the standard for SS now.

**Pull request closed without merging**
