### PR TITLE
Add icons and colours to the message tab.

### PR DESCRIPTION
**Pull request by Firesphere**
Add Icons and colours to the Messages. Colours and icons are based on bootstrap defaults.

Todo: Remove the inline icons and use FA

image

Sorry for the huge screenshot, but taking screenshots on a 4K screen is a bit awkward

### CODE REVIEW

**Comment by robbieaverill** [comment]
At the moment errors are shown in red (text included). Can that be retained?

**Comment by Firesphere** [comment]
I did not change anything on that actually.... You mean the error text actually red? Probably not an issue, but to be honest, I think making the message itself red is a bad for readability? (Need to check :) )

**Comment by sachajudd** [comment]
@Firesphere https://github.com/lekoala/silverstripe-debugbar/blob/master/docs/en/messages.md I see you've removed the red error text, this could be #a94442 to match the icon error color instead? Or instead of bootstrap how about using SS4 alert colors to keep with consistency?

**Comment by Firesphere** [comment]
Ah, woops :D restored that :)

**Comment by sachajudd** [comment]
@Firesphere Will you be doing a separate P.R for FA icons? After talking to the Style Council they agree that SS4 colors would be more consistent across the toolbar and to stick with the main alert colors red, orange and blue. The hex codes are the following: 
Alert & Error + text: #d30000
Warning: #f46b00
Info, Debug & Notice: #0071c4

**Comment by Firesphere** [comment]
@sachajudd Yes, probably combined with the move to use Yarn/Webpack for the CSS and JS.

**Comment by Firesphere** [comment]
@sachajudd I don't think the color for Debug should be blue, it's a very strange colour for a bug, the green color I had originally makes more sense :)

**Comment by robbieaverill** [comment]
> I don't think the color for Debug should be blue, it's a very strange colour for a bug, the green color I had originally makes more sense :)

Green normally means "success", "OK" or "good"

**Comment by sachajudd** [comment]
@Firesphere How about #3fa142 for Debug? 🙂

**Comment by Firesphere** [comment]
That looks pretty good @sachajudd :) Much better than blue :D Updated with the colours

**Comment by sachajudd** [comment]
I agree with @robbieaverill though. I still think blue would be a reasonable colour to choose since it is more of an indication icon for users.

**Comment by Firesphere** [comment]
As every debugger in Visual Studio, IntelliJ, etc. has a green bug-icon. I disagree to using blue, it's an illogical color to choose for debugging. Leaving at that, I'll close this PR and leave it up to someone else to pick up adding icons and colours.

**Comment by sachajudd** [comment]
What would be another color that doesn't mean success? 🙂 I think this would be a great addition to the module!

**Comment by Firesphere** [comment]
I would not think of the colour as meaning anything like success. All IDE's use a _green bug_ icon for starting the debugger. I do not believe it's meaning in a traffic-light kind of situation is confusing to any developer. I press a green bug icon to start the debugger, I get a _green_ highlighted tab in my IDE. It makes much more sense to therefore also use a green bug icon in a debugbar, than choosing an arbitrary colour that is _not_ associated with debugging.

**Pull request closed without merging**
