### PR TITLE
Add a Header collector

### PR DESCRIPTION
**Pull request by Firesphere**
Show a list of all the headers in the request. Re: #124 , I decided it would be better off being part of the original code. The extension point is something I might look at later.

### CODE REVIEW

**Comment by Firesphere** [comment]
Build failures are due to a composer issue, not my changes.
Cheers

**Comment by lekoala** [comment]
maybe we could just add a yml flag to enable or disable that collector, in the same fashion as   email_collector: true ... maybe header_collector: true

**Comment by Firesphere** [comment]
Ow, yeah! Absolutely.

I wasn't aware the email_collector could be enabled and disabled via YML :D Absolutely can do

**Comment by Firesphere** [comment]
Added the configuration option, haven't been able to properly test due to a configuration error on my test instance, but as far as I can tell from the generated JSON, it works as intended.

**Comment by lekoala** [comment]
Looks good to me!

**Comment by Firesphere** [comment]
Care to create a release version for this? Probably a minor SemVer release? (Added functionality, no breaking changes)

**Comment by lekoala** [comment]
@robbieaverill could you have a look and create a release? i don't have at hand your handy script that create a nice list of commits :-)

also if you could check how to fix the travis build? i merged this https://github.com/lekoala/silverstripe-debugbar/pull/123 but it's targeted at version 2.0 but i don't see any good reason not to apply the changes to the master as well since it's broken anyway.

**Comment by robbieaverill** [comment]
Hey @lekoala, the log tool I use for small changelogs is this bash alias:

```
# gcl 1.2.3...1.2.4
alias gcl='git log --oneline --pretty=format:"* %s (%an) - %h" --no-merges'
```

To fix the builds you can merge the 2.0 branch into the master branch 👍

**Comment by lekoala** [comment]
@robbieaverill @Firesphere  i created the release. i've realized there were quite a lot of fixes waiting to be included. as far as i can tell, they are all welcome addition to the current branch.

**Pull request merged**
